spring:
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  h2:
    console:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
#          facebook:
#            client-id: ${FACEBOOK_CLIENT_ID}
#            client-secret: ${FACEBOOK_CLIENT_SECRET}
#            scope:
#              - public_profile
#              - email

server:
  forward-headers-strategy: framework

app:
  mail:
    from: ${APP_MAIL_FROM:${SPRING_MAIL_USERNAME}}
  sms:
    account-sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    from-number: ${TWILIO_FROM_NUMBER}
  otp:
    expose-dev-code: false
